Fix Split chat not working on Livestreams
bttv-android/bttv pull request #688
Opened 2024-08-30 11:07 UTC by Zerwin

Fixes #673 

## Changes
Twitch changed chat messages in Live Streams to be LinearLayouts with the chat_message_item as a child. This fixes it to target the child rather than the LinearLayout to make Split Chat work again.

## Checklist

 - [x] My change builds
 - [x] I tested my change
 - [ ] ~~I use the "bttv_" prefix for all resources I propose~~
 - [ ] ~~When adding a string I also added it to the `bttv.Res.strings` Enum and `res/values/strings.xml` (in `mod`) and `res/values/public.xml` (in `disass`)~~
 - [ ] ~~If my change is significant enough, I added it to the CHANGELOG.md under `master`~~
 - [ ] ~~I'll add myself and everyone else who contributed to this change to the contributors list using [all-contributors](https://allcontributors.org/docs/en/bot/usage)~~
 - [x] I license my changes according to the [MIT License](https://github.com/bttv-android/bttv/blob/master/LICENSE).

2024-08-30 11:42 UTC, FoseFx commented
This only highlights the text, not the whole "row"

![image](https://github.com/user-attachments/assets/c0719ed8-6662-448b-8b8b-f7405105c094)

2024-08-30 12:09 UTC, Zerwin commented
The LinearLayout only stretches as far as the text, not the row. I thought of trying to set the width to the whole space, but that might introduce other bugs that could be a headache to deal with.

2024-12-23 22:28 UTC, Zerwin commented
I made it so that comments are as wide as the parent element now. This should make the entire "row" colored. I tested it for a bit and at least couldn't immediately find any bugs because of this change.

2024-12-26 11:16 UTC, FoseFx requested changes
Highly appreciate your help!
Only one minor thing I'd like to have changed with this.

2024-12-26 11:16 UTC, FoseFx commented on mod/app/src/main/java/bttv/SplitChat.java
> +        // If view is a LinearLayout, check the childrens to find chat_message_item
```suggestion
        // make sure we only change chat message items,
        // which are LinearLayouts with chat_message_item children.
        // Anything else is ignored.
```

2024-12-26 11:16 UTC, FoseFx commented on mod/app/src/main/java/bttv/SplitChat.java
> +                if (nestedChild.getId() == ResUtil.getResourceId(context, "chat_message_item", "id")) {
before the loop (before the `if` even), initialize a variable `chatMessageItemResId` with `ResUtil.getResourceId(context, "chat_message_item", "id")`. This way it does not have to be looked up in every iteration.

Also do `chommentRootViewResId` for consistency.

```suggestion
                if (nestedChild.getId() == chatMessageItemResId) {
```

2024-12-26 11:16 UTC, FoseFx commented on mod/app/src/main/java/bttv/SplitChat.java
>          boolean hasChatMessageId = view.getId() == ResUtil.getResourceId(context, "chat_message_item", "id");
```suggestion
        boolean hasChatMessageId = view.getId() == chatMessageItemResId;
```

2024-12-26 11:16 UTC, FoseFx commented on mod/app/src/main/java/bttv/SplitChat.java
>          boolean hasChommentRootId = view.getId() == ResUtil.getResourceId(context, "chomment_root_view", "id");
```suggestion
        boolean hasChommentRootId = view.getId() == chommentRootViewResId;
```

2024-12-26 11:16 UTC, FoseFx commented on mod/app/src/main/java/bttv/SplitChat.java
> +            Log.i(TAG, "view skipped, as it's not a chat message or chomment, " + viewHolder.toString() + " ID: " + view.getId() + " View: " + view.toString() + " Expected ID: " + ResUtil.getResource
```suggestion
            Log.d(TAG, "view skipped, as it's not a chat message or chomment, " + viewHolder.toString() + " ID: " + view.getId() + " View: " + view.toString() + " Expected ID: " + chatMessageItemResId + " or " + chommentRootViewResId);
```

2024-12-27 02:14 UTC, Zerwin commented
This should be all of the changes

2024-12-27 11:05 UTC, FoseFx approved these changes
🎉️

2024-12-27 11:05 UTC, merged